name: Build and Test

on:
  workflow_dispatch:  # Add manual trigger option
  push:
    branches: [ main ]
    paths:
      - '**/*.go'      # Only run on Go file changes
      - 'go.mod'       # Run on dependency changes
      - 'go.sum'
      - 'Makefile'     # Run on build config changes
      - '.github/workflows/build-test.yml'  # Run when this workflow changes
      - 'ui/**/*'      # Run on UI changes
  pull_request:
    branches: [ main ]
    paths:
      - '**/*.go'      # Only run on Go file changes
      - 'go.mod'       # Run on dependency changes
      - 'go.sum'
      - 'Makefile'     # Run on build config changes
      - '.github/workflows/build-test.yml'  # Run when this workflow changes
      - 'ui/**/*'      # Run on UI changes

# Explicitly set minimal permissions
permissions:
  contents: read
  actions: read
  security-events: write

jobs:
  build-go:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24'
        check-latest: true
    
    - name: Download UI build artifacts
      uses: actions/download-artifact@v4
      with:
        name: ui-dist
        path: ui/dist
    
    - name: Build
      run: make build
    
    - name: Test
      run: make test 